LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

include $(SDK_DIR)/Android.def

LOCAL_PRELINK_MODULE := false

LOCAL_MODULE := libhiflash
ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_MODULE)

LOCAL_MODULE_TAGS := optional

ifndef CFG_HI_CFLAGS
CFG_HI_CFLAGS = -Wall -g -march=armv5te -ggdb
endif

LOCAL_CFLAGS := $(CFG_HI_CFLAGS)
LOCAL_CFLAGS += -DLOG_TAG=\"$(LOCAL_MODULE)\"

LOCAL_SRC_FILES :=  src/hi_flash.c
LOCAL_SRC_FILES +=  src/nand.c
LOCAL_SRC_FILES +=  src/spi_raw.c
LOCAL_SRC_FILES +=  src/nand_raw.c
LOCAL_SRC_FILES +=  src/emmc_raw.c

LOCAL_C_INCLUDES := $(MSP_API_INCLUDE)
LOCAL_C_INCLUDES += $(MSP_DRV_INCLUDE)
LOCAL_C_INCLUDES += $(MSP_UNF_INCLUDE)
LOCAL_C_INCLUDES += $(COMMON_UNF_INCLUDE)
LOCAL_C_INCLUDES += $(COMMON_DRV_INCLUDE)
LOCAL_C_INCLUDES += $(LOCAL_PATH)/include

LOCAL_SHARED_LIBRARIES := libcutils libutils libdl

include $(BUILD_SHARED_LIBRARY)
